name: Main branch Build and Deployment
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build-sam:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'no-deploy')
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v3
    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
    # This step will configure environment variables to be used by all steps
    # involving AWS interaction further down (in this job)
    - name: AWS credentials configuration
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build serverless application using SAM
      run: sam build --use-container
    - name: Deploy to AWS using SAM
      run: |
        sam deploy --resolve-s3 --resolve-image-repos --capabilities CAPABILITY_IAM \
           --no-confirm-changeset --no-fail-on-empty-changeset
